import { CanvasConfig, CardConfig, StylePreset, TweetData } from "../types";

export const SAMPLE_TWEETS: { id: string; label: string; data: TweetData }[] = [
  {
    id: "sample-naval",
    label: "Naval Ravikant Quote",
    data: {
      id: "1351234567890",
      url: "https://x.com/naval/status/1351234567890",
      text: "Seek wealth, not money or status. Wealth is having assets that earn while you sleep. Money is how we transfer time and wealth. Status is your place in the social hierarchy.",
      createdAt: "2024-03-15T14:20:00.000Z",
      author: {
        name: "Naval",
        handle: "naval",
        avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80",
        verified: true,
        verifiedType: "blue",
      },
      metrics: {
        likes: 42800,
        retweets: 9320,
        replies: 1240,
        views: 1850000,
        bookmarks: 14200,
      },
      media: [],
    },
  },
  {
    id: "sample-tech",
    label: "Product Announcement",
    data: {
      id: "1359876543210",
      url: "https://x.com/techcreator/status/1359876543210",
      text: "🚀 Introducing Poetify 2.0!\n\nTurn any tweet or idea into pixel-perfect studio grade graphics in seconds.\n\n✨ Glassmorphism cards\n🎨 4K Gradient themes\n⚡ Instant Clipboard copy\n\nTry it now for free 👇",
      createdAt: "2024-07-22T09:30:00.000Z",
      author: {
        name: "Alex Rivera",
        handle: "alexrivera_ui",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80",
        verified: true,
        verifiedType: "blue",
      },
      metrics: {
        likes: 18500,
        retweets: 3410,
        replies: 620,
        views: 520000,
        bookmarks: 4800,
      },
      media: [
        "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80",
      ],
    },
  },
  {
    id: "sample-minimal",
    label: "Minimalist Insight",
    data: {
      id: "1355555555555",
      url: "https://x.com/designthinker/status/1355555555555",
      text: "Simplicity is not the absence of clutter, that's a consequence of simplicity. Simplicity is somehow essentially describing the purpose and place of an object and product.",
      createdAt: "2024-05-10T18:45:00.000Z",
      author: {
        name: "Design Thought",
        handle: "designthought",
        avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=250&q=80",
        verified: true,
        verifiedType: "gold",
      },
      metrics: {
        likes: 8900,
        retweets: 1820,
        replies: 245,
        views: 290000,
        bookmarks: 3100,
      },
      media: [],
    },
  },
  {
    id: "sample-quote",
    label: "Short Quote Line",
    data: {
      id: "1362222222222",
      url: "https://x.com/leadwithwhy/status/1362222222222",
      text: "A team is not a group of people who work together. A team is a group of people who trust each other.",
      createdAt: "2024-09-02T11:15:00.000Z",
      author: {
        name: "Jordan Blake",
        handle: "leadwithwhy",
        avatar:
          "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80",
        verified: true,
        verifiedType: "blue",
      },
      metrics: {
        likes: 26400,
        retweets: 6100,
        replies: 380,
        views: 940000,
        bookmarks: 9200,
      },
      media: [],
    },
  },
];

export const GRADIENT_PRESETS = [
  {
    id: "frosted-sunset",
    name: "Frosted Sunset",
    value: "linear-gradient(135deg, #f97316 0%, #e11d48 100%)",
  },
  {
    id: "frosted-indigo",
    name: "Frosted Indigo",
    value: "linear-gradient(135deg, #6366f1 0%, #a855f7 100%)",
  },
  {
    id: "frosted-emerald",
    name: "Emerald Cyan",
    value: "linear-gradient(135deg, #10b981 0%, #06b6d4 100%)",
  },
  {
    id: "glow-sunset",
    name: "Glow Sunset",
    value: "linear-gradient(135deg, #ff7e5f 0%, #feb47b 100%)",
  },
  {
    id: "aurora-borealis",
    name: "Aurora Glow",
    value: "linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)",
  },
  {
    id: "deep-ocean",
    name: "Deep Blue",
    value: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
  },
  {
    id: "neon-cyber",
    name: "Neon Cyber",
    value: "linear-gradient(135deg, #f72585 0%, #7209b7 50%, #4cc9f0 100%)",
  },
  {
    id: "peach-sorbet",
    name: "Peach Sorbet",
    value: "linear-gradient(135deg, #ff9a9e 0%, #fecfef 99%, #fecfef 100%)",
  },
  {
    id: "obsidian-mesh",
    name: "Obsidian Slate",
    value: "linear-gradient(135deg, #18181b 0%, #27272a 50%, #09090b 100%)",
  },
  {
    id: "emerald-mint",
    name: "Emerald Mint",
    value: "linear-gradient(135deg, #11998e 0%, #38ef7d 100%)",
  },
  {
    id: "hyper-violet",
    name: "Hyper Violet",
    value: "linear-gradient(135deg, #654ea3 0%, #eaafc8 100%)",
  },
  {
    id: "warm-ember",
    name: "Warm Ember",
    value: "linear-gradient(135deg, #ff4e50 0%, #f9d423 100%)",
  },
  {
    id: "cosmic-darkness",
    name: "Cosmic Indigo",
    value: "linear-gradient(135deg, #1a103c 0%, #2b1b54 50%, #4a2d82 100%)",
  },
  {
    id: "clean-soft-gray",
    name: "Clean Studio",
    value: "linear-gradient(135deg, #e0eafc 0%, #cfdef3 100%)",
  },
  {
    id: "rose-gold",
    name: "Rose Gold",
    value: "linear-gradient(135deg, #f6d365 0%, #fda085 100%)",
  },
];

export const STYLE_PRESETS: StylePreset[] = [
  {
    id: "frosted-glass-pro",
    name: "Frosted Glass Pro",
    category: "vibrant",
    canvasConfig: {
      frameMode: "canvas",
      padding: 64,
      bgType: "gradient",
      bgGradient: "linear-gradient(135deg, #f97316 0%, #e11d48 100%)",
      bgNoise: true,
    },
    cardConfig: {
      layout: "tweet",
      theme: "glass",
      borderRadius: 20,
      shadow: "elevated",
      border: true,
      borderColor: "rgba(255, 255, 255, 0.25)",
      fontFamily: "sans",
      fontSize: 16,
      showMetrics: true,
      showTwitterLogo: true,
    },
  },
  {
    id: "studio-classic",
    name: "Studio Classic",
    category: "classic",
    canvasConfig: {
      frameMode: "canvas",
      padding: 64,
      bgType: "gradient",
      bgGradient: "linear-gradient(135deg, #ff7e5f 0%, #feb47b 100%)",
      bgNoise: true,
    },
    cardConfig: {
      layout: "tweet",
      theme: "light",
      borderRadius: 16,
      shadow: "heavy",
      border: true,
      borderColor: "rgba(255, 255, 255, 0.4)",
      fontFamily: "sans",
      fontSize: 16,
      showMetrics: true,
      showTwitterLogo: true,
    },
  },
  {
    id: "obsidian-glass",
    name: "Obsidian Glass",
    category: "dark",
    canvasConfig: {
      frameMode: "canvas",
      padding: 72,
      bgType: "gradient",
      bgGradient: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
      bgNoise: true,
    },
    cardConfig: {
      layout: "tweet",
      theme: "glass",
      borderRadius: 20,
      shadow: "glow",
      border: true,
      borderColor: "rgba(255, 255, 255, 0.15)",
      fontFamily: "sans",
      fontSize: 16,
      showMetrics: true,
      showTwitterLogo: true,
    },
  },
  {
    id: "neon-cyberpunk",
    name: "Neon Cyber",
    category: "vibrant",
    canvasConfig: {
      frameMode: "canvas",
      padding: 64,
      bgType: "gradient",
      bgGradient: "linear-gradient(135deg, #f72585 0%, #7209b7 50%, #4cc9f0 100%)",
      bgNoise: true,
    },
    cardConfig: {
      layout: "tweet",
      theme: "dark",
      borderRadius: 24,
      shadow: "glow",
      border: true,
      borderColor: "rgba(247, 37, 133, 0.3)",
      fontFamily: "sans",
      fontSize: 17,
      showMetrics: true,
      showTwitterLogo: true,
    },
  },
  {
    id: "minimal-studio",
    name: "Minimal Studio",
    category: "minimal",
    canvasConfig: {
      frameMode: "canvas",
      padding: 80,
      bgType: "gradient",
      bgGradient: "linear-gradient(135deg, #e0eafc 0%, #cfdef3 100%)",
      bgNoise: false,
    },
    cardConfig: {
      layout: "tweet",
      theme: "light",
      borderRadius: 12,
      shadow: "medium",
      border: true,
      borderColor: "rgba(0, 0, 0, 0.06)",
      fontFamily: "sans",
      fontSize: 16,
      showMetrics: false,
      showTwitterLogo: true,
    },
  },
  {
    id: "retro-typewriter",
    name: "Serif Journal",
    category: "retro",
    canvasConfig: {
      frameMode: "canvas",
      padding: 64,
      bgType: "gradient",
      bgGradient: "linear-gradient(135deg, #f6d365 0%, #fda085 100%)",
      bgNoise: true,
    },
    cardConfig: {
      layout: "tweet",
      theme: "paper",
      borderRadius: 8,
      shadow: "heavy",
      border: true,
      borderColor: "rgba(120, 80, 40, 0.2)",
      fontFamily: "serif",
      fontSize: 17,
      showMetrics: true,
      showTwitterLogo: false,
    },
  },

  // ── Quote posters ──────────────────────────────────────────────────────────
  // Full-bleed typographic quote graphics (the Instagram quote-post format).
  {
    id: "bold-statement",
    name: "Bold Statement",
    category: "quote",
    canvasConfig: {
      frameMode: "bare",
      aspectRatio: "1:1",
      padding: 96,
    },
    cardConfig: {
      layout: "poster",
      theme: "light",
      fontFamily: "display",
      borderRadius: 0,
      border: false,
      shadow: "none",
      textAlignment: "center",
      posterFontSize: 46,
      posterAutoFit: true,
      posterMark: "none",
      posterInsetBorder: false,
      showAttribution: true,
      showAvatar: false,
      showTwitterLogo: false,
      showWatermark: false,
    },
  },
  {
    id: "midnight-quote",
    name: "Midnight Quote",
    category: "quote",
    canvasConfig: {
      frameMode: "bare",
      aspectRatio: "4:5",
      padding: 88,
    },
    cardConfig: {
      layout: "poster",
      theme: "obsidian",
      fontFamily: "display",
      borderRadius: 0,
      border: false,
      shadow: "none",
      textAlignment: "left",
      posterFontSize: 44,
      posterAutoFit: true,
      posterMark: "bar",
      posterInsetBorder: false,
      showAttribution: true,
      showAvatar: false,
      showTwitterLogo: false,
      showWatermark: false,
    },
  },
  {
    id: "gradient-poster",
    name: "Gradient Poster",
    category: "quote",
    canvasConfig: {
      frameMode: "bare",
      aspectRatio: "1:1",
      padding: 96,
      bgType: "gradient",
      bgGradient: "linear-gradient(135deg, #1a103c 0%, #2b1b54 50%, #4a2d82 100%)",
    },
    cardConfig: {
      layout: "poster",
      theme: "gradient",
      fontFamily: "sans",
      borderRadius: 0,
      border: false,
      shadow: "none",
      textAlignment: "center",
      posterFontSize: 44,
      posterAutoFit: true,
      posterMark: "glyph",
      posterInsetBorder: false,
      showAttribution: true,
      showAvatar: true,
      showTwitterLogo: false,
      showWatermark: false,
    },
  },
  {
    id: "editorial-serif",
    name: "Editorial Serif",
    category: "quote",
    canvasConfig: {
      frameMode: "bare",
      aspectRatio: "4:5",
      padding: 80,
    },
    cardConfig: {
      layout: "poster",
      theme: "paper",
      fontFamily: "serif",
      borderRadius: 0,
      border: false,
      shadow: "none",
      textAlignment: "left",
      posterFontSize: 42,
      posterAutoFit: true,
      posterMark: "none",
      posterInsetBorder: true,
      showAttribution: true,
      showAvatar: false,
      showTwitterLogo: false,
      showWatermark: false,
    },
  },
  {
    id: "framed-quote-card",
    name: "Framed Quote Card",
    category: "quote",
    canvasConfig: {
      frameMode: "canvas",
      aspectRatio: "1:1",
      padding: 72,
      bgType: "gradient",
      bgGradient: "linear-gradient(135deg, #f97316 0%, #e11d48 100%)",
      bgNoise: true,
    },
    cardConfig: {
      layout: "poster",
      theme: "glass",
      fontFamily: "display",
      borderRadius: 24,
      border: true,
      borderColor: "rgba(255, 255, 255, 0.25)",
      shadow: "elevated",
      textAlignment: "center",
      posterFontSize: 36,
      posterAutoFit: true,
      posterMark: "glyph",
      posterInsetBorder: false,
      showAttribution: true,
      showAvatar: true,
      showTwitterLogo: false,
      showWatermark: false,
    },
  },
];

export const DEFAULT_CANVAS_CONFIG: CanvasConfig = {
  aspectRatio: "auto",
  frameMode: "canvas",
  padding: 56,
  bgType: "gradient",
  bgGradient: "linear-gradient(135deg, #654ea3 0%, #eaafc8 100%)",
  bgSolidColor: "#1e1b4b",
  bgBlur: 0,
  bgNoise: true,
};

export const DEFAULT_CARD_CONFIG: CardConfig = {
  layout: "tweet",
  theme: "dark",
  customCardBg: "#0f172a",
  customTextColor: "#f8fafc",
  borderRadius: 16,
  shadow: "heavy",
  border: true,
  borderColor: "rgba(255, 255, 255, 0.12)",
  fontFamily: "sans",
  fontSize: 16,
  cardWidth: 576,
  textAlignment: "left",
  posterFontSize: 44,
  posterAutoFit: true,
  posterMark: "none",
  posterInsetBorder: false,
  showAttribution: true,
  showAvatar: true,
  showVerified: true,
  showTwitterLogo: true,
  showTimestamp: true,
  showMetrics: true,
  showMedia: true,
  showQuote: true,
  showWatermark: false,
  watermarkText: "Created with PoetCraft",
  metricFormat: "compact",
};
